<!DOCTYPE html>
<!-- Vue Form qui affiche le formulaire permettant d'ajouter des images -->

<html>
  <head>
    <meta charset="utf-8"/>
    <title>Scroll4fun - Ajout</title>

    <!-- # Fichiers CSS # -->
      <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
      <link href='css/bootstrap.css' rel='stylesheet' type='text/css'>
      <link href='css/index.css' rel='stylesheet' type='text/css'>
      <link href='css/form.css' rel='stylesheet' type='text/css'>
      <link href='css/footer.css' rel='stylesheet' type='text/css'>
    <!-- # Fichiers CSS # -->

  </head>
  
  <body>
    <!-- # Top de la page # -->
      <div>
        <!-- Titres -->
          <div class="title">Scroll4fun</div>
          <div class="name-bar">Ranaivo Kevin | Rémy Nora</div>
        <!-- Titres -->

        <!-- Barre de navigation -->
        <nav class="navbar navbar-default" role="navigation">
          <ul class="nav navbar-nav">
            <li><a href="/">Accueil</a></li>
            <li><a href="/theme">Thème</a></li>
            <li><a href="/form">Ajouter</a></li>
          </ul>
        </nav>
        <!-- Barre de navigation -->
      </div>
    <!-- # Top de la page # -->
    
    <!-- # Mid de la page # -->
    <!-- # Affichage du formulaire permettant l'upload d'images # -->
    <div class="wrapper">
      <!-- Formulaire -->
      <form enctype="multipart/form-data" action="/upload" method="POST" id="Add" class="simpleBox" >
        <div class="center" >Ajout d'une image</div>
        <label for = "text"> Nom de l'image : </label> 
        <input type="text" required="required" name = "title"/>  
        <p>
          <br><label for="vartheme">Thème de la photo :</label><br/>
          <!-- Checkbox -->
          <div class = "specialtext">
            <input checked type="radio" name="theme" value="Game"/><label for="Game"> Game</label><br/>
            <input type="radio" name="theme" value="SuperHero"/><label for="SuperHero"> SuperHero</label><br/>
            <input type="radio" name="theme" value="Animal"/><label for="Animal"> Animal</label><br/>
            <input type="radio" name="theme" value = "Food"/><label for="Food">Food</label><br/>
            <input type="radio" name="theme" value="Work"/><label for="Work">Work</label><br/>
            <input type="radio" name="theme"  alue="Other"/><label for="Other">Other</label><br/>
          </div>
        </p>
        <input type="file" name="file" required="required"/>
        <input type="submit" value="Valider" class="myButton"/>
      </form>
      <div class="push"></div>
    </div>

        <!-- # Bas de la page # -->
          <div id="footer" class="footer">
            <div>
              <p> &copy; 2016 Ranaivo Rémy</p>
            </div>
          </div>
        <!-- # Fin Bas de la page # -->
    <!-- # Mid de la page # -->
    <!-- # Affichage du formulaire permettant l'upload d'images # -->
  </body>
</html>
