<!DOCTYPE html>
<!-- Vue Form qui affiche les différents thèmes regroupant les images associées -->

<html>
  <head>
    <meta charset="utf-8"/>
    <title>Scroll4fun - Thèmes</title>
       
    <!-- Fichiers CSS -->
      <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
      <link href='css/bootstrap.css' rel='stylesheet' type='text/css'>
      <link href='css/index.css' rel='stylesheet' type='text/css'>
      <link href='css/theme.css' rel='stylesheet' type='text/css'>
      <link href='css/footer.css' rel='stylesheet' type='text/css'>
    <!-- Fichiers CSS -->

  </head>

  <body>
    <!-- # Top de la page # -->
      <div>
        <!-- Titres -->
          <div class="title">Scroll4fun</div>
          <div class="name-bar">Ranaivo Kevin | Rémy Nora</div>
        <!-- Titres -->

        <!-- Barre de navigation -->
        <nav class="navbar navbar-default" role="navigation">
          <ul class="nav navbar-nav">
            <li><a href="/">Accueil</a></li>
            <li><a href="/theme">Thème</a></li>
            <li><a href="/form">Ajouter</a></li>
          </ul>
        </nav>
        <!-- Barre de navigation -->
      </div>
    <!-- # Top de la page # -->

    <!-- # Mid de la page # -->
    <!-- # Affichage des thèmes par box # -->
    <div class="wrapper">
      <div id="link" class="clearfix grid"> 
        
        <!-- Box thème : GAME -->
        <figure class="effect-oscar">
          <img src="/uploads/game.jpg" height="432" width="960"/>
          <figcaption>
            <h2>Game</h2>
            <p>Images drôles : Game<br/><a href="/theme/game">Voir plus</a></p>         
          </figcaption>
        </figure>

        <!-- Box thème : ANIMAL -->
        <figure class="effect-oscar ">
          <img src="/uploads/animal.jpg" width="960" height="432"/>
          <figcaption>
            <h2>Animal</h2>
            <p>Images drôles : Animal<br/><a href="/theme/animal">Voir plus</a></p>          
          </figcaption>
        </figure>

        <!-- Box thème : SUPERHERO -->
        <figure class="effect-oscar">
          <img src="/uploads/bat.jpg" width="960" height="432"/>
          <figcaption>
            <h2>Super Hero</h2>
            <p>Images drôles : Super Hero<br><a href="/theme/superhero">Voir plus</a></p>            
          </figcaption>
        </figure>

        <!-- Box thème : FOOD -->
        <figure class="effect-oscar">
          <img src="/uploads/food.jpg" width="960" height="432"/>
          <figcaption>
            <h2>Food</h2>
            <p>Images drôles : Food<br><a href="/theme/food" title="2" >Voir plus</a></p>            
          </figcaption>
        </figure>

        <!-- Box thème : WORK -->
        <figure class="effect-oscar">
          <img src="/uploads/work.jpeg" width="960" height="432"/>
          <figcaption>
            <h2>Work</h2>
            <p>Images drôles : Work<br><a href="/theme/work" title="2" >Voir plus</a></p>            
          </figcaption>
        </figure>

        <!-- Box thème : OTHER -->
        <figure class="effect-oscar">
          <img src="/uploads/other.jpg" width="960" height="432"/>
          <figcaption>
            <h2>Other</h2>
            <p>Images drôles : Other<br><a href="/theme/other" title="2" >Voir plus</a></p>            
          </figcaption>
        </figure>
      </div>
      <div class="push"></div>
    </div>
    <!-- # Mid de la page # -->
    <!-- # Affichage des thèmes par box # -->

    <!-- # Bas de la page # -->
      <div id="footer" class="footer">
        <div>
          <p> &copy; 2016 Ranaivo Rémy </p>
        </div>
      </div>  
    <!-- # Fin Bas de la page # -->
  </body>
</html>


